title:              Stefan Beenen
email:              stefan.beenen@hotmail.com
description:        hi
author:             Stefan Beenen
baseurl:            ""
url:                "stefanbeenen.nl"
permalink:          /kb/:title

# Social Profiles
twitter_username:
github_username: stoeffoe
facebook_username:
instagram_username:
linkedin_username: stefanbeenen

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
